<?php
//echo $_SERVER['SERVER_ADDR'];

//echo $_SERVER['SERVER_NAME'];
// echo $_SERVER['SERVER_SOFTWARE'];
//echo $_SERVER['SERVER_METHOD'];

// ECHO $_SERVER['REMOTE_ADDR'];

// echo $_SERVER['REMOTE_PORT'];

// ECHO $_SERVER['SCRIPT_NAME'];

// ECHO $_SERVER['PHP_SELF'];
// ECHO $_SERVER['SERVER_NAME'];
// ECHO $_SERVER['HTTP_HOST'];
// ECHO $_SERVER['PHP_REFERER'];
// ECHO $_SERVER['PHP_USER_AGENT'];
// ECHO $_SERVER['SCRIPT_NAME'];



?>